name: Development pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Lint code
      run: npm run lint

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Start Express.js server
      run: node server.js &
      env:
        NODE_ENV: test

    - name: Wait for server to be ready
      run: |
        node server.js &
        echo "Waiting for server to start..."

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman integration tests
      run: newman run Postman/GenSoft.postman_collection.json

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: postman-test-results
        path: newman/  # Newman will output test results to the newman/ directory

  SonarCloud_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          projectBaseDir: ${{ github.workspace }}/
          args:
            -Dsonar.projectKey=valeriVidev_GenSoft-API
            -Dsonar.organization=gensoft
